name: ci
on: [pull_request]
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Spin up containers
        run: make up
      - name: Health check
        run: docker exec warehouse pg_isready
      - name: Run CI test
        run: make ci